package v1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_OpenShiftServiceCatalogConfig = map[string]string{
	"":                "OpenShiftServiceCatalogConfig holds the necessary configuration options for running the Service Catalog",
	"enabled":         "enabled specifies if Service Catalog should be installed and started in the cluster",
	"serverArguments": "serverArguments are key value pairs that will override the default set of arguments.  ServerArguments may include Feature Gates & Admission Plugins.  If you specify an invalid argument the server will not start. These values may cause invalid configurations.\",",
}

func (OpenShiftServiceCatalogConfig) SwaggerDoc() map[string]string {
	return map_OpenShiftServiceCatalogConfig
}

// AUTO-GENERATED FUNCTIONS END HERE
